/**
 * Registered figure recipes. A publication may only name recipes listed
 * here; each recipe's component is trusted code reviewed with this repo.
 */
export interface RecipeDefinition {
  id: string;
  description: string;
  minFixtures: number;
  maxFixtures: number;
  interactive: boolean;
  controls: string[];
  /** Fixture kind every fixture passed to this recipe must have. */
  /** Fixture kind the recipe draws; several allowed kinds are written "a|b". */
  fixtureKind: string;
}

export const RECIPES: readonly RecipeDefinition[] = [
  {
    id: "address-anatomy.v1",
    description: "One valid address split into prefix, separator, version, program and checksum.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "address",
  },
  {
    id: "address-checksum-lab.v1",
    description: "Validation stages for public fixtures, with single-character substitution.",
    minFixtures: 2,
    maxFixtures: 6,
    interactive: true,
    controls: ["Choose public address fixture", "Change one character", "Compare checksum families"],
    fixtureKind: "address",
  },
  {
    id: "program-regrouping.v1",
    description: "Witness program bits regrouped from 8-bit bytes into 5-bit characters.",
    minFixtures: 2,
    maxFixtures: 2,
    interactive: false,
    controls: [],
    fixtureKind: "address",
  },
  {
    id: "mnemonic-card.v1",
    description: "A public BIP39 test phrase laid out as a numbered backup card.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "mnemonic",
  },
  {
    id: "entropy-word-pipeline.v1",
    description: "Entropy and checksum bits cut into 11-bit groups and looked up as words.",
    minFixtures: 2,
    maxFixtures: 6,
    interactive: true,
    controls: ["Choose public fixture", "Toggle 128/256-bit fixture", "Reveal 11-bit groups"],
    fixtureKind: "mnemonic",
  },
  {
    id: "seed-derivation.v1",
    description: "Mnemonic and passphrase through PBKDF2-HMAC-SHA512 into a 64-byte seed.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "mnemonic",
  },
  {
    id: "master-key-split.v1",
    description: "Seed through HMAC-SHA512 into master private key and chain code.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bip32-seed",
  },
  {
    id: "derivation-tree.v1",
    description: "A fixed BIP32 key tree seen with the master xprv or xpub, with a hardened boundary.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: true,
    controls: ["Expand a branch", "Switch public/private view", "Toggle hardened boundary"],
    fixtureKind: "bip32-seed",
  },
  {
    id: "extended-key-layout.v1",
    description: "The 78-byte extended key payload of one node, public versus private.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bip32-seed",
  },
  {
    id: "two-serializations.v1",
    description: "The txid and wtxid preimages of one transaction, to scale.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "transaction",
  },
  {
    id: "transaction-anatomy.v1",
    description: "A serialized transaction by field, with txid, wtxid and BIP143 signing lenses.",
    minFixtures: 1,
    maxFixtures: 4,
    interactive: true,
    controls: ["Switch txid/wtxid preimage view", "Select a public transaction fixture", "Inspect BIP143 signing preimage"],
    fixtureKind: "transaction",
  },
  {
    id: "weight-meter.v1",
    description: "Weight as four units per base byte and one per witness byte.",
    minFixtures: 1,
    maxFixtures: 4,
    interactive: false,
    controls: [],
    fixtureKind: "transaction",
  },
  {
    id: "psbt-layout.v1",
    description: "A newly created PSBT as an envelope of key-value maps.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "psbt-trace",
  },
  {
    id: "psbt-envelope.v1",
    description: "Replay of BIP174's published role trace, field by field.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: true,
    controls: ["Advance through a reviewed trace", "Inspect added fields", "Compare partial/final states"],
    fixtureKind: "psbt-trace",
  },
  {
    id: "unknown-fields.v1",
    description: "Two PSBTs with unknown key-value pairs combined without losing them.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "psbt-combine",
  },
  {
    id: "schnorr-signature-layout.v1",
    description: "A 32-byte x-only public key, a message, and a 64-byte signature split into r and s.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "schnorr-vector",
  },
  {
    id: "schnorr-verification.v1",
    description: "BIP 340 Verify run step by step on published valid and invalid vectors.",
    minFixtures: 2,
    maxFixtures: 12,
    interactive: true,
    controls: ["Choose public valid/invalid vector", "Change a message fixture", "Reveal verifier stages"],
    fixtureKind: "schnorr-vector",
  },
  {
    id: "challenge-preimage.v1",
    description: "The tagged challenge-hash input for messages of several lengths, to scale.",
    minFixtures: 2,
    maxFixtures: 6,
    interactive: false,
    controls: [],
    fixtureKind: "schnorr-vector",
  },
  {
    id: "taproot-tweak.v1",
    description: "Internal key, Merkle root and TapTweak giving the output key, for published vectors.",
    minFixtures: 1,
    maxFixtures: 2,
    interactive: false,
    controls: [],
    fixtureKind: "taproot-tree",
  },
  {
    id: "taproot-commitment.v1",
    description: "One published script tree: key-path and script-path spends, and what each reveals.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: true,
    controls: ["Switch key/script path", "Select a leaf", "Reveal only the proof material"],
    fixtureKind: "taproot-tree",
  },
  {
    id: "taproot-sigmsg.v1",
    description: "The BIP 341 signature message of one published key-path spend, item by item.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "taproot-keyspend",
  },
  {
    id: "tapscript-witness.v1",
    description: "One recorded script-path witness split into what BIP 341 checks and what BIP 342 runs.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "tapscript-case",
  },
  {
    id: "tapscript-trace.v1",
    description: "Recorded, verified tapscript executions from Bitcoin Core's test cases, step by step.",
    minFixtures: 2,
    maxFixtures: 6,
    interactive: true,
    controls: ["Step a reviewed trace", "Compare success/failure fixtures", "Inspect signature count"],
    fixtureKind: "tapscript-case",
  },
  {
    id: "sigops-budget.v1",
    description: "The per-input signature budget of recorded witnesses: 50 plus witness size, 50 per signature.",
    minFixtures: 1,
    maxFixtures: 6,
    interactive: false,
    controls: [],
    fixtureKind: "tapscript-case",
  },
  {
    id: "p2sh-commitment.v1",
    description: "A P2SH output's 20-byte hash beside the redeem script its spend reveals.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "p2sh-spend",
  },
  {
    id: "p2sh-two-stage.v1",
    description: "BIP 16's checks on pinned spends: push-only scriptSig, hash match, then the redeem script or witness.",
    minFixtures: 1,
    maxFixtures: 4,
    interactive: true,
    controls: ["Choose a pinned spend", "Step through both evaluations", "Reveal the redeem script"],
    fixtureKind: "p2sh-spend",
  },
  {
    id: "p2sh-wrapped.v1",
    description: "Where pinned P2SH spends carry their signatures: scriptSig or witness.",
    minFixtures: 2,
    maxFixtures: 4,
    interactive: false,
    controls: [],
    fixtureKind: "p2sh-spend",
  },
  {
    id: "timelock-fields.v1",
    description: "Bitcoin Core's CLTV/CSV test transactions with BIP 65's and BIP 112's checks; fields editable, re-checked by the tested model.",
    minFixtures: 2,
    maxFixtures: 12,
    interactive: true,
    controls: ["Choose absolute or relative lock", "Change a fixture field", "Compare height and time units"],
    fixtureKind: "timelock-case",
  },
  {
    id: "timelock-pinned-fields.v1",
    description: "How consensus reads the version, nLockTime and nSequence of published transactions.",
    minFixtures: 2,
    maxFixtures: 4,
    interactive: false,
    controls: [],
    fixtureKind: "timelock-bip-tx",
  },
  {
    id: "timelock-ranges.v1",
    description: "nLockTime's height/time split and nSequence's two units, at their ranges.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "timelock-encoding",
  },
  {
    id: "versionbits-state-machine.v1",
    description: "BIP 9 and BIP 8 deployment states over a schematic run of retarget periods, with pinned parameters and hypothetical signalling.",
    minFixtures: 1,
    maxFixtures: 4,
    interactive: true,
    controls: ["Step through retarget periods", "Choose a published deployment", "Toggle signalling count"],
    fixtureKind: "versionbits-deployment|versionbits-guideline",
  },
  {
    id: "versionbits-field.v1",
    description: "A block's nVersion as BIP 9 reads it: top bits 001 and the deployment bits.",
    minFixtures: 1,
    maxFixtures: 4,
    interactive: false,
    controls: [],
    fixtureKind: "versionbits-deployment",
  },
  {
    id: "versionbits-record.v1",
    description: "BIP 9's recorded deployments, cross-checked dates, and the lock-in periods their activation heights imply.",
    minFixtures: 1,
    maxFixtures: 4,
    interactive: false,
    controls: [],
    fixtureKind: "versionbits-deployment",
  },
];

export const RECIPE_MAP = new Map(RECIPES.map((r) => [r.id, r]));
