/**
 * Registered figure recipes. A publication may only name recipes listed
 * here; each recipe's component is trusted code reviewed with this repo.
 */
export interface RecipeDefinition {
  id: string;
  description: string;
  minFixtures: number;
  maxFixtures: number;
  interactive: boolean;
  controls: string[];
  /** Fixture kind every fixture passed to this recipe must have. */
  /** Fixture kind the recipe draws; several allowed kinds are written "a|b". */
  fixtureKind: string;
  /**
   * Drawn in the illustration-kit style (decision D3): rendered without the
   * figure card or the Interactive / Worked example tabs.
   */
  drawing?: boolean;
}

export const RECIPES: readonly RecipeDefinition[] = [
  {
    id: "address-anatomy.v1",
    description: "One valid address split into prefix, separator, version, program and checksum.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "address",
  },
  {
    id: "address-checksum-lab.v1",
    description: "Validation stages for public fixtures, with single-character substitution.",
    minFixtures: 2,
    maxFixtures: 6,
    interactive: true,
    controls: ["Choose public address fixture", "Change one character", "Compare checksum families"],
    fixtureKind: "address",
  },
  {
    id: "program-regrouping.v1",
    description: "Witness program bits regrouped from 8-bit bytes into 5-bit characters.",
    minFixtures: 2,
    maxFixtures: 2,
    interactive: false,
    controls: [],
    fixtureKind: "address",
  },
  {
    id: "mnemonic-card.v1",
    description: "A public BIP39 test phrase laid out as a numbered backup card.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "mnemonic",
    drawing: true,
  },
  {
    id: "entropy-word-pipeline.v1",
    description: "Entropy and checksum bits cut into 11-bit groups and looked up as words.",
    minFixtures: 2,
    maxFixtures: 6,
    interactive: true,
    controls: ["Choose public fixture", "Toggle 128/256-bit fixture", "Reveal 11-bit groups"],
    fixtureKind: "mnemonic",
    drawing: true,
  },
  {
    id: "seed-derivation.v1",
    description: "Mnemonic and passphrase through PBKDF2-HMAC-SHA512 into a 64-byte seed.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "mnemonic",
    drawing: true,
  },
  {
    id: "entropy-bits.v1",
    description: "The entropy of one public sample as a grid of bits beside its hexadecimal form.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "mnemonic",
    drawing: true,
  },
  {
    id: "checksum-storyboard.v1",
    description: "Storyboard: entropy into SHA-256, the first bits kept as the checksum, appended to make n × 11 bits.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "mnemonic",
    drawing: true,
  },
  {
    id: "wordlist-index.v1",
    description: "Eleven bits as a number that picks one card from a stack of 2,048, with the list's first entries.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "mnemonic",
    drawing: true,
  },
  {
    id: "last-word-odds.v1",
    description: "All 2,048 candidate last words for a fixed prefix, the valid ones filled.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "mnemonic",
    drawing: true,
  },
  {
    id: "passphrase-seeds.v1",
    description: "The same words with two passphrases: two unrelated 64-byte seeds.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "mnemonic",
    drawing: true,
  },
  {
    id: "mnemonic-chain.v1",
    description: "Entropy, words, seed and keys as three separate steps.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "mnemonic",
    drawing: true,
  },
  {
    id: "master-key-split.v1",
    description: "Seed through HMAC-SHA512 into master private key and chain code.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bip32-seed",
  },
  {
    id: "derivation-tree.v1",
    description: "A fixed BIP32 key tree seen with the master xprv or xpub, with a hardened boundary.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: true,
    controls: ["Expand a branch", "Switch public/private view", "Toggle hardened boundary"],
    fixtureKind: "bip32-seed",
  },
  {
    id: "extended-key-layout.v1",
    description: "The 78-byte extended key payload of one node, public versus private.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bip32-seed",
  },
  {
    id: "two-serializations.v1",
    description: "The txid and wtxid preimages of one transaction, to scale.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "transaction",
  },
  {
    id: "transaction-anatomy.v1",
    description: "A serialized transaction by field, with txid, wtxid and BIP143 signing lenses.",
    minFixtures: 1,
    maxFixtures: 4,
    interactive: true,
    controls: ["Switch txid/wtxid preimage view", "Select a public transaction fixture", "Inspect BIP143 signing preimage"],
    fixtureKind: "transaction",
  },
  {
    id: "weight-meter.v1",
    description: "Weight as four units per base byte and one per witness byte.",
    minFixtures: 1,
    maxFixtures: 4,
    interactive: false,
    controls: [],
    fixtureKind: "transaction",
  },
  {
    id: "psbt-layout.v1",
    description: "A newly created PSBT as an envelope of key-value maps.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "psbt-trace",
  },
  {
    id: "psbt-envelope.v1",
    description: "Replay of BIP174's published role trace, field by field.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: true,
    controls: ["Advance through a reviewed trace", "Inspect added fields", "Compare partial/final states"],
    fixtureKind: "psbt-trace",
  },
  {
    id: "unknown-fields.v1",
    description: "Two PSBTs with unknown key-value pairs combined without losing them.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "psbt-combine",
  },
  {
    id: "schnorr-signature-layout.v1",
    description: "The verifier as a machine with three input slots: a 32-byte x-only key, a message of any length, and a 64-byte signature r ‖ s.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "schnorr-vector",
    drawing: true,
  },
  {
    id: "schnorr-byte-sizes.v1",
    description: "BIP 340's fixed sizes on one byte ruler: DER signature, r ‖ s, compressed key and x-only key.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "schnorr-vector",
    drawing: true,
  },
  {
    id: "schnorr-equation.v1",
    description: "The verification equation s⋅G = R + e⋅P as a balance, with where each term comes from.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "schnorr-vector",
    drawing: true,
  },
  {
    id: "schnorr-verify-story.v1",
    description: "Storyboard: one valid published vector through Verify, one frame per step.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "schnorr-vector",
    drawing: true,
  },
  {
    id: "schnorr-verification.v1",
    description: "BIP 340 Verify run step by step on published valid and invalid vectors.",
    minFixtures: 2,
    maxFixtures: 12,
    interactive: true,
    controls: ["Choose public valid/invalid vector", "Change a message fixture", "Reveal verifier stages"],
    fixtureKind: "schnorr-vector",
    drawing: true,
  },
  {
    id: "schnorr-fail-gates.v1",
    description: "Where each published vector stops among Verify's eight checks.",
    minFixtures: 2,
    maxFixtures: 14,
    interactive: false,
    controls: [],
    fixtureKind: "schnorr-vector",
    drawing: true,
  },
  {
    id: "challenge-preimage.v1",
    description: "The tagged challenge-hash input for messages of several lengths, to scale.",
    minFixtures: 2,
    maxFixtures: 6,
    interactive: false,
    controls: [],
    fixtureKind: "schnorr-vector",
    drawing: true,
  },
  {
    id: "schnorr-even-y.v1",
    description: "One x coordinate, two y values: the even one kept for keys and for R; two secret keys per x-only key.",
    minFixtures: 2,
    maxFixtures: 2,
    interactive: false,
    controls: [],
    fixtureKind: "schnorr-vector",
    drawing: true,
  },
  {
    id: "taproot-tweak.v1",
    description: "Internal key, Merkle root and TapTweak giving the output key, for published vectors.",
    minFixtures: 1,
    maxFixtures: 2,
    interactive: false,
    controls: [],
    fixtureKind: "taproot-tree",
    drawing: true,
  },
  {
    id: "taproot-commitment.v1",
    description: "One published script tree: key-path and script-path spends, and what each reveals.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: true,
    controls: ["Switch key/script path", "Select a leaf", "Reveal only the proof material"],
    fixtureKind: "taproot-tree",
    drawing: true,
  },
  {
    id: "taproot-sigmsg.v1",
    description: "The BIP 341 signature message of one published key-path spend, item by item.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "taproot-keyspend",
    drawing: true,
  },
  {
    id: "taproot-witness-stacks.v1",
    description: "The key-path and script-path witnesses of one output as stacks of items.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "taproot-tree",
    drawing: true,
  },
  {
    id: "taproot-verifier-story.v1",
    description: "Storyboard: the verifier rebuilds the commitment for one leaf, step by step.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "taproot-tree",
    drawing: true,
  },
  {
    id: "taproot-reveals.v1",
    description: "What an observer of the chain sees of a key-path and a script-path spend.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "taproot-tree",
    drawing: true,
  },
  {
    id: "taproot-depth.v1",
    description: "A published tree with each leaf's control block drawn to scale.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "taproot-tree",
    drawing: true,
  },
  {
    id: "tapscript-witness.v1",
    description: "One recorded script-path witness split into what BIP 341 checks and what BIP 342 runs.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "tapscript-case",
    drawing: true,
  },
  {
    id: "tapscript-order.v1",
    description: "BIP 342's validation order as six gates, with every recorded witness drawn as a lane.",
    minFixtures: 1,
    maxFixtures: 6,
    interactive: false,
    controls: [],
    fixtureKind: "tapscript-case",
    drawing: true,
  },
  {
    id: "tapscript-sig-rules.v1",
    description: "What a signature opcode does with each shape of key and signature, with the recorded cases in each tray.",
    minFixtures: 1,
    maxFixtures: 6,
    interactive: false,
    controls: [],
    fixtureKind: "tapscript-case",
    drawing: true,
  },
  {
    id: "tapscript-multisig.v1",
    description: "CHECKMULTISIG failing in a recorded witness, and the CHECKSIGADD chain BIP 342 suggests instead.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "tapscript-case",
    drawing: true,
  },
  {
    id: "tapscript-stack-story.v1",
    description: "Storyboard: one recorded success witness, opcode by opcode, with the stack as plates.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "tapscript-case",
    drawing: true,
  },
  {
    id: "tapscript-trace.v1",
    description: "Recorded, verified tapscript executions from Bitcoin Core's test cases, step by step.",
    minFixtures: 2,
    maxFixtures: 6,
    interactive: true,
    controls: ["Step a reviewed trace", "Compare success/failure fixtures", "Inspect signature count"],
    fixtureKind: "tapscript-case",
    drawing: true,
  },
  {
    id: "sigops-budget.v1",
    description: "The per-input signature budget of recorded witnesses: 50 plus witness size, 50 per signature.",
    minFixtures: 1,
    maxFixtures: 6,
    interactive: false,
    controls: [],
    fixtureKind: "tapscript-case",
    drawing: true,
  },
  {
    id: "tapscript-sig-pays.v1",
    description: "What a checked and an empty signature add to the budget and what their checks cost.",
    minFixtures: 1,
    maxFixtures: 6,
    interactive: false,
    controls: [],
    fixtureKind: "tapscript-case",
    drawing: true,
  },
  {
    id: "tapscript-op-success.v1",
    description: "The OP_SUCCESS case: a trapdoor in the decoder, against a script that runs and fails.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "tapscript-case",
    drawing: true,
  },
  {
    id: "tapscript-minimalif.v1",
    description: "OP_IF accepts only an empty vector or 0x01: a recorded witness that fits and one that does not.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "tapscript-case",
    drawing: true,
  },
  {
    id: "p2sh-commitment.v1",
    description: "A P2SH output's 20-byte hash beside the redeem script its spend reveals.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "p2sh-spend",
  },
  {
    id: "p2sh-two-stage.v1",
    description: "BIP 16's checks on pinned spends: push-only scriptSig, hash match, then the redeem script or witness.",
    minFixtures: 1,
    maxFixtures: 4,
    interactive: true,
    controls: ["Choose a pinned spend", "Step through both evaluations", "Reveal the redeem script"],
    fixtureKind: "p2sh-spend",
  },
  {
    id: "p2sh-wrapped.v1",
    description: "Where pinned P2SH spends carry their signatures: scriptSig or witness.",
    minFixtures: 2,
    maxFixtures: 4,
    interactive: false,
    controls: [],
    fixtureKind: "p2sh-spend",
  },
  {
    id: "timelock-fields.v1",
    description: "Bitcoin Core's CLTV/CSV test transactions with BIP 65's and BIP 112's checks; fields editable, re-checked by the tested model.",
    minFixtures: 2,
    maxFixtures: 12,
    interactive: true,
    controls: ["Choose absolute or relative lock", "Change a fixture field", "Compare height and time units"],
    fixtureKind: "timelock-case",
  },
  {
    id: "timelock-pinned-fields.v1",
    description: "How consensus reads the version, nLockTime and nSequence of published transactions.",
    minFixtures: 2,
    maxFixtures: 4,
    interactive: false,
    controls: [],
    fixtureKind: "timelock-bip-tx",
  },
  {
    id: "timelock-ranges.v1",
    description: "nLockTime's height/time split and nSequence's two units, at their ranges.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "timelock-encoding",
  },
  {
    id: "versionbits-state-machine.v1",
    description: "BIP 9 and BIP 8 deployment states over a schematic run of retarget periods, with pinned parameters and hypothetical signalling.",
    minFixtures: 1,
    maxFixtures: 4,
    interactive: true,
    controls: ["Step through retarget periods", "Choose a published deployment", "Toggle signalling count"],
    fixtureKind: "versionbits-deployment|versionbits-guideline",
  },
  {
    id: "versionbits-field.v1",
    description: "A block's nVersion as BIP 9 reads it: top bits 001 and the deployment bits.",
    minFixtures: 1,
    maxFixtures: 4,
    interactive: false,
    controls: [],
    fixtureKind: "versionbits-deployment",
  },
  {
    id: "versionbits-record.v1",
    description: "BIP 9's recorded deployments, cross-checked dates, and the lock-in periods their activation heights imply.",
    minFixtures: 1,
    maxFixtures: 4,
    interactive: false,
    controls: [],
    fixtureKind: "versionbits-deployment",
  },
  {
    id: "wallet-path-walk.v1",
    description: "Steps down a published BIP 44-shaped path level by level to the key and address, from BIP 84 and BIP 86 vectors.",
    minFixtures: 1,
    maxFixtures: 3,
    interactive: true,
    controls: ["Choose a published path scheme", "Step through path levels", "Switch receive/change"],
    fixtureKind: "wallet-path-vector",
  },
  {
    id: "wallet-path-levels.v1",
    description: "BIP 44's five path levels, their meaning, and where hardened derivation stops.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "wallet-path-vector",
  },
  {
    id: "wallet-path-schemes.v1",
    description: "Purposes 44, 84 and 86 side by side: the same path shape, and what each BIP fixes beyond it.",
    minFixtures: 2,
    maxFixtures: 3,
    interactive: false,
    controls: [],
    fixtureKind: "wallet-path-vector",
  },
  {
    id: "descriptor-anatomy.v1",
    description: "Published descriptors from BIPs 380–386 split into their expressions, with keys, expanded scripts and the checksum check.",
    minFixtures: 1,
    maxFixtures: 10,
    interactive: true,
    controls: ["Choose a published descriptor", "Highlight a key expression", "Check the descriptor checksum"],
    fixtureKind: "descriptor-vector",
  },
  {
    id: "descriptor-checksum.v1",
    description: "BIP 380's character-to-symbol expansion and checksum for one published descriptor.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "descriptor-vector",
  },
  {
    id: "descriptor-expressions.v1",
    description: "BIP 380's index of script expressions, with where each may appear and what it produces.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "descriptor-index",
  },
  {
    id: "musig2-chain-view.v1",
    description: "Signers behind a boundary; what the chain sees of a MuSig2 key path spend: one key, one signature.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "musig2-session",
    drawing: true,
  },
  {
    id: "musig2-keyagg.v1",
    description: "MuSig2 key aggregation with coefficients in two key orders, against the plain sum of the keys.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "musig2-keyagg",
    drawing: true,
  },
  {
    id: "musig2-coefficients.v1",
    description: "Storyboard: the key-list hash, a hashed coefficient, and the second key's coefficient of 1.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "musig2-session",
    drawing: true,
  },
  {
    id: "musig2-rounds.v1",
    description: "BIP 327 signing sessions from the published sig_agg vectors: key aggregation, nonce round, session values, partial signatures, final BIP 340 signature.",
    minFixtures: 1,
    maxFixtures: 4,
    interactive: true,
    controls: ["Step through signing rounds", "Choose a published vector", "Reveal aggregated values"],
    fixtureKind: "musig2-session",
    drawing: true,
  },
  {
    id: "musig2-round-story.v1",
    description: "Storyboard: one published signing session, stage by stage, around the same table.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "musig2-session",
    drawing: true,
  },
  {
    id: "musig2-nonce-once.v1",
    description: "Schematic: a secret nonce is used by Sign once and then refused.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "musig2-session",
    drawing: true,
  },
  {
    id: "musig2-psig-checks.v1",
    description: "BIP 327's partial-signature verification cases and their outcomes.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "musig2-psig-checks",
    drawing: true,
  },
  {
    id: "sp-address.v1",
    description: "The parts of a version 0 silent payment address.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "sp-vector",
    drawing: true,
  },
  {
    id: "sp-ecdh.v1",
    description: "Storyboard, symbolic: Alice and Bob reach the same Diffie-Hellman point across an open network.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "sp-vector",
    drawing: true,
  },
  {
    id: "sp-derive-story.v1",
    description: "Storyboard: one published vector's full derivation, from address keys to the receiver's scan.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "sp-vector",
    drawing: true,
  },
  {
    id: "silent-payment-derivation.v1",
    description: "BIP 352 send-and-receive vectors: input keys, input hash, shared secret, outputs, and the receiver's scan.",
    minFixtures: 1,
    maxFixtures: 8,
    interactive: true,
    controls: ["Choose a published vector", "Switch sender/receiver view", "Reveal shared-secret steps"],
    fixtureKind: "sp-vector",
    drawing: true,
  },
  {
    id: "sp-input-eligibility.v1",
    description: "Which inputs of published BIP 352 vectors contribute a key to the shared secret.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "sp-eligibility",
    drawing: true,
  },
  {
    id: "sp-scan-loop.v1",
    description: "The receiver's scan as a counter that stops at the first missing output.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "sp-vector",
    drawing: true,
  },
  {
    id: "sp-labels.v1",
    description: "A receiver's labeled addresses share their scan-key characters.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "sp-vector",
    drawing: true,
  },
  {
    id: "gcs-filter.v1",
    description: "BIP 158 basic filters of published testnet blocks: elements, hashed values, Golomb-Rice coding and membership queries.",
    minFixtures: 1,
    maxFixtures: 8,
    interactive: true,
    controls: ["Choose a published block", "Test a fixture script against the filter", "Reveal Golomb-Rice coding"],
    fixtureKind: "bf-block",
  },
  {
    id: "golomb-rice-code.v1",
    description: "BIP 158's Golomb-Rice table for P = 2, recomputed, and one P = 19 code from a published filter.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bf-golomb",
  },
  {
    id: "filter-header-chain.v1",
    description: "BIP 157 filter hashes and headers of published blocks, each header committing to the previous one.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bf-chain",
  },
  {
    id: "v2-handshake.v1",
    description: "BIP 324 packet vectors: key exchange, key schedule and one encrypted packet, step by step.",
    minFixtures: 1,
    maxFixtures: 8,
    interactive: true,
    controls: ["Step through the handshake", "Choose a published packet vector", "Compare v1 and v2 framing"],
    fixtureKind: "v2-vector",
  },
  {
    id: "v1-v2-framing.v1",
    description: "Per-message overhead of v1 and v2 framing.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "v2-framing",
  },
  {
    id: "v2-rekey.v1",
    description: "FSChaCha20Poly1305 nonces and keys across the 224-packet rekey boundary.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "v2-rekey",
  },
  {
    id: "bip322-virtual-tx.v1",
    description: "BIP 322 vectors: the message hash, the to_spend and to_sign virtual transactions, and the verdict.",
    minFixtures: 1,
    maxFixtures: 8,
    interactive: true,
    controls: ["Choose a published vector", "Switch to_spend/to_sign view", "Reveal the message hash"],
    fixtureKind: "bip322-vector",
  },
  {
    id: "bip322-formats.v1",
    description: "BIP 322's signature formats, read from the BIP's table.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bip322-formats",
  },
  {
    id: "bip322-verdicts.v1",
    description: "The three verification outcomes, one published vector each.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bip322-verdicts",
  },
];

export const RECIPE_MAP = new Map(RECIPES.map((r) => [r.id, r]));
