/**
 * Registered figure recipes. A publication may only name recipes listed
 * here; each recipe's component is trusted code reviewed with this repo.
 */
export interface RecipeDefinition {
  id: string;
  description: string;
  minFixtures: number;
  maxFixtures: number;
  interactive: boolean;
  controls: string[];
  /** Fixture kind every fixture passed to this recipe must have. */
  /** Fixture kind the recipe draws; several allowed kinds are written "a|b". */
  fixtureKind: string;
  /**
   * Drawn in the illustration-kit style (decision D3): rendered without the
   * figure card or the Interactive / Worked example tabs.
   */
  drawing?: boolean;
}

export const RECIPES: readonly RecipeDefinition[] = [
  {
    id: "address-anatomy.v1",
    description: "One valid address as a ribbon of characters, its five parts bracketed and named.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "address",
    drawing: true,
  },
  {
    id: "address-alphabet.v1",
    description: "Bech32's 32 data characters in value order, and the four left out.",
    minFixtures: 0,
    maxFixtures: 0,
    interactive: false,
    controls: [],
    fixtureKind: "address",
    drawing: true,
  },
  {
    id: "address-case.v1",
    description: "Lowercase and uppercase spellings of one address decode alike; a mixed-case string is refused first.",
    minFixtures: 3,
    maxFixtures: 3,
    interactive: false,
    controls: [],
    fixtureKind: "address",
    drawing: true,
  },
  {
    id: "address-polymod-story.v1",
    description: "Storyboard: data characters to values, the prefix expanded, polymod, a result of exactly 1.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "address",
    drawing: true,
  },
  {
    id: "address-checksum-lab.v1",
    description: "Validation stages for public fixtures, with single-character substitution.",
    minFixtures: 2,
    maxFixtures: 6,
    interactive: true,
    controls: ["Choose public address fixture", "Change one character", "Compare checksum families"],
    fixtureKind: "address",
    drawing: true,
  },
  {
    id: "address-typo-story.v1",
    description: "Storyboard: a valid address, one character changed, rejected without position or correction.",
    minFixtures: 2,
    maxFixtures: 2,
    interactive: false,
    controls: [],
    fixtureKind: "address",
    drawing: true,
  },
  {
    id: "address-two-constants.v1",
    description: "One polymod, two accepted constants, and a v1 program with the wrong family refused at the end.",
    minFixtures: 3,
    maxFixtures: 3,
    interactive: false,
    controls: [],
    fixtureKind: "address",
    drawing: true,
  },
  {
    id: "address-q-weakness.v1",
    description: "Schematic: q characters inserted before a final p leave a Bech32 checksum valid.",
    minFixtures: 0,
    maxFixtures: 0,
    interactive: false,
    controls: [],
    fixtureKind: "address",
    drawing: true,
  },
  {
    id: "program-regrouping.v1",
    description: "Witness program bits regrouped from 8-bit bytes into 5-bit characters.",
    minFixtures: 2,
    maxFixtures: 2,
    interactive: false,
    controls: [],
    fixtureKind: "address",
    drawing: true,
  },
  {
    id: "address-script.v1",
    description: "From address to output script: version character to opcode, then push length and program.",
    minFixtures: 2,
    maxFixtures: 2,
    interactive: false,
    controls: [],
    fixtureKind: "address",
    drawing: true,
  },
  {
    id: "mnemonic-card.v1",
    description: "A public BIP39 test phrase laid out as a numbered backup card.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "mnemonic",
    drawing: true,
  },
  {
    id: "entropy-word-pipeline.v1",
    description: "Entropy and checksum bits cut into 11-bit groups and looked up as words.",
    minFixtures: 2,
    maxFixtures: 6,
    interactive: true,
    controls: ["Choose public fixture", "Toggle 128/256-bit fixture", "Reveal 11-bit groups"],
    fixtureKind: "mnemonic",
    drawing: true,
  },
  {
    id: "seed-derivation.v1",
    description: "Mnemonic and passphrase through PBKDF2-HMAC-SHA512 into a 64-byte seed.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "mnemonic",
    drawing: true,
  },
  {
    id: "entropy-bits.v1",
    description: "The entropy of one public sample as a grid of bits beside its hexadecimal form.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "mnemonic",
    drawing: true,
  },
  {
    id: "checksum-storyboard.v1",
    description: "Storyboard: entropy into SHA-256, the first bits kept as the checksum, appended to make n × 11 bits.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "mnemonic",
    drawing: true,
  },
  {
    id: "wordlist-index.v1",
    description: "Eleven bits as a number that picks one card from a stack of 2,048, with the list's first entries.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "mnemonic",
    drawing: true,
  },
  {
    id: "last-word-odds.v1",
    description: "All 2,048 candidate last words for a fixed prefix, the valid ones filled.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "mnemonic",
    drawing: true,
  },
  {
    id: "passphrase-seeds.v1",
    description: "The same words with two passphrases: two unrelated 64-byte seeds.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "mnemonic",
    drawing: true,
  },
  {
    id: "mnemonic-chain.v1",
    description: "Entropy, words, seed and keys as three separate steps.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "mnemonic",
    drawing: true,
  },
  {
    id: "master-key-split.v1",
    description: "Seed through HMAC-SHA512, cut in half into master private key and chain code.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bip32-seed",
    drawing: true,
  },
  {
    id: "hd-extended-key.v1",
    description: "An extended key as two plates, key over chain code; neutering swaps k for K and keeps c.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bip32-seed",
    drawing: true,
  },
  {
    id: "hd-hmac-inputs.v1",
    description: "The HMAC data of a normal and a hardened step on one byte ruler, with the index's top bit.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bip32-seed",
    drawing: true,
  },
  {
    id: "hd-child-story.v1",
    description: "Storyboard: one normal child step, from the parent's values through HMAC-SHA512 to the published child.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bip32-seed",
    drawing: true,
  },
  {
    id: "derivation-tree.v1",
    description: "A fixed BIP32 key tree seen with the master xprv or xpub, with a hardened boundary.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: true,
    controls: ["Expand a branch", "Switch public/private view", "Toggle hardened boundary"],
    fixtureKind: "bip32-seed",
    drawing: true,
  },
  {
    id: "hd-two-routes.v1",
    description: "A normal child's public key by CKDpriv and by CKDpub, meeting at the same key.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bip32-seed",
    drawing: true,
  },
  {
    id: "hd-sharing.v1",
    description: "Schematic: parties that hold only extended public keys, and what each can do.",
    minFixtures: 0,
    maxFixtures: 0,
    interactive: false,
    controls: [],
    fixtureKind: "bip32-seed",
    drawing: true,
  },
  {
    id: "hd-weakness-story.v1",
    description: "Storyboard: a parent xpub plus a leaked normal child private key gives the parent private key.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bip32-seed",
    drawing: true,
  },
  {
    id: "extended-key-layout.v1",
    description: "The 78-byte extended key payload plus checksum of one node, public versus private, as packets.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bip32-seed",
    drawing: true,
  },
  {
    id: "hd-fingerprint.v1",
    description: "Public key through Hash160 to an identifier whose first four bytes are the fingerprint.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bip32-seed",
    drawing: true,
  },
  {
    id: "two-serializations.v1",
    description: "Storyboard: the serialized tape hashed whole (wtxid), then without marker, flag and witness (txid).",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "transaction",
    drawing: true,
  },
  {
    id: "witness-field.v1",
    description: "The witness section byte by byte: an empty field, then count, lengths, signature and key.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "transaction",
    drawing: true,
  },
  {
    id: "witness-commitment.v1",
    description: "Schematic block: the txid tree into the header, the wtxid tree into a coinbase commitment.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "transaction",
    drawing: true,
  },
  {
    id: "transaction-anatomy.v1",
    description: "A serialized transaction on a byte grid, with txid, wtxid and BIP143 signing lenses.",
    minFixtures: 1,
    maxFixtures: 4,
    interactive: true,
    controls: ["Switch txid/wtxid preimage view", "Select a public transaction fixture", "Inspect BIP143 signing preimage"],
    fixtureKind: "transaction",
    drawing: true,
  },
  {
    id: "nested-input.v1",
    description: "A P2SH-wrapped P2WPKH input: the program pushed in the scriptSig, signature and key in the witness.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "transaction",
    drawing: true,
  },
  {
    id: "weight-meter.v1",
    description: "Bytes projected into weight: four units per base byte and one per witness-related byte.",
    minFixtures: 1,
    maxFixtures: 4,
    interactive: false,
    controls: [],
    fixtureKind: "transaction",
    drawing: true,
  },
  {
    id: "sighash-reuse.v1",
    description: "Schematic: the original digest hashes the whole transaction per input; BIP143 hashes summaries once.",
    minFixtures: 0,
    maxFixtures: 0,
    interactive: false,
    controls: [],
    fixtureKind: "transaction",
    drawing: true,
  },
  {
    id: "bip143-preimage.v1",
    description: "The ten-item BIP143 preimage of one published input as a packet diagram, and its sighash.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "transaction",
    drawing: true,
  },
  {
    id: "amount-storyboard.v1",
    description: "Storyboard: an offline signer, the amount it cannot see, and why a wrong one fails.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "transaction",
    drawing: true,
  },
  {
    id: "psbt-layout.v1",
    description: "A newly created PSBT byte by byte: magic, one global record, a separator per map.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "psbt-trace",
    drawing: true,
  },
  {
    id: "psbt-records.v1",
    description: "Two partial-signature records in one map: same type, different key data.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "psbt-trace",
    drawing: true,
  },
  {
    id: "psbt-envelope.v1",
    description: "BIP174's published role trace: the envelope passed from role to role.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: true,
    controls: ["Advance through a reviewed trace", "Inspect added fields", "Compare partial/final states"],
    fixtureKind: "psbt-trace",
    drawing: true,
  },
  {
    id: "psbt-role-story.v1",
    description: "Storyboard: each published state of the trace as a miniature envelope.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "psbt-trace",
    drawing: true,
  },
  {
    id: "psbt-signer-display.v1",
    description: "What a signer can show before signing: input amounts, outputs and fee.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "psbt-trace",
    drawing: true,
  },
  {
    id: "psbt-utxo-check.v1",
    description: "The signer's check that a non-witness UTXO hashes to the txid its input names.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "psbt-trace",
    drawing: true,
  },
  {
    id: "psbt-combine.v1",
    description: "Two signers' copies of one input map merged by the Combiner.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "psbt-trace",
    drawing: true,
  },
  {
    id: "psbt-finalize.v1",
    description: "Input maps after the Input Finalizer: kept, added and cleared records.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "psbt-trace",
    drawing: true,
  },
  {
    id: "unknown-fields.v1",
    description: "Two PSBTs with unknown key-value pairs combined without losing them.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "psbt-combine",
    drawing: true,
  },
  {
    id: "schnorr-signature-layout.v1",
    description: "The verifier as a machine with three input slots: a 32-byte x-only key, a message of any length, and a 64-byte signature r ‖ s.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "schnorr-vector",
    drawing: true,
  },
  {
    id: "schnorr-byte-sizes.v1",
    description: "BIP 340's fixed sizes on one byte ruler: DER signature, r ‖ s, compressed key and x-only key.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "schnorr-vector",
    drawing: true,
  },
  {
    id: "schnorr-equation.v1",
    description: "The verification equation s⋅G = R + e⋅P as a balance, with where each term comes from.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "schnorr-vector",
    drawing: true,
  },
  {
    id: "schnorr-verify-story.v1",
    description: "Storyboard: one valid published vector through Verify, one frame per step.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "schnorr-vector",
    drawing: true,
  },
  {
    id: "schnorr-verification.v1",
    description: "BIP 340 Verify run step by step on published valid and invalid vectors.",
    minFixtures: 2,
    maxFixtures: 12,
    interactive: true,
    controls: ["Choose public valid/invalid vector", "Change a message fixture", "Reveal verifier stages"],
    fixtureKind: "schnorr-vector",
    drawing: true,
  },
  {
    id: "schnorr-fail-gates.v1",
    description: "Where each published vector stops among Verify's eight checks.",
    minFixtures: 2,
    maxFixtures: 14,
    interactive: false,
    controls: [],
    fixtureKind: "schnorr-vector",
    drawing: true,
  },
  {
    id: "challenge-preimage.v1",
    description: "The tagged challenge-hash input for messages of several lengths, to scale.",
    minFixtures: 2,
    maxFixtures: 6,
    interactive: false,
    controls: [],
    fixtureKind: "schnorr-vector",
    drawing: true,
  },
  {
    id: "schnorr-even-y.v1",
    description: "One x coordinate, two y values: the even one kept for keys and for R; two secret keys per x-only key.",
    minFixtures: 2,
    maxFixtures: 2,
    interactive: false,
    controls: [],
    fixtureKind: "schnorr-vector",
    drawing: true,
  },
  {
    id: "taproot-tweak.v1",
    description: "Internal key, Merkle root and TapTweak giving the output key, for published vectors.",
    minFixtures: 1,
    maxFixtures: 2,
    interactive: false,
    controls: [],
    fixtureKind: "taproot-tree",
    drawing: true,
  },
  {
    id: "taproot-commitment.v1",
    description: "One published script tree: key-path and script-path spends, and what each reveals.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: true,
    controls: ["Switch key/script path", "Select a leaf", "Reveal only the proof material"],
    fixtureKind: "taproot-tree",
    drawing: true,
  },
  {
    id: "taproot-sigmsg.v1",
    description: "The BIP 341 signature message of one published key-path spend, item by item.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "taproot-keyspend",
    drawing: true,
  },
  {
    id: "taproot-witness-stacks.v1",
    description: "The key-path and script-path witnesses of one output as stacks of items.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "taproot-tree",
    drawing: true,
  },
  {
    id: "taproot-verifier-story.v1",
    description: "Storyboard: the verifier rebuilds the commitment for one leaf, step by step.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "taproot-tree",
    drawing: true,
  },
  {
    id: "taproot-reveals.v1",
    description: "What an observer of the chain sees of a key-path and a script-path spend.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "taproot-tree",
    drawing: true,
  },
  {
    id: "taproot-depth.v1",
    description: "A published tree with each leaf's control block drawn to scale.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "taproot-tree",
    drawing: true,
  },
  {
    id: "tapscript-witness.v1",
    description: "One recorded script-path witness split into what BIP 341 checks and what BIP 342 runs.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "tapscript-case",
    drawing: true,
  },
  {
    id: "tapscript-order.v1",
    description: "BIP 342's validation order as six gates, with every recorded witness drawn as a lane.",
    minFixtures: 1,
    maxFixtures: 6,
    interactive: false,
    controls: [],
    fixtureKind: "tapscript-case",
    drawing: true,
  },
  {
    id: "tapscript-sig-rules.v1",
    description: "What a signature opcode does with each shape of key and signature, with the recorded cases in each tray.",
    minFixtures: 1,
    maxFixtures: 6,
    interactive: false,
    controls: [],
    fixtureKind: "tapscript-case",
    drawing: true,
  },
  {
    id: "tapscript-multisig.v1",
    description: "CHECKMULTISIG failing in a recorded witness, and the CHECKSIGADD chain BIP 342 suggests instead.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "tapscript-case",
    drawing: true,
  },
  {
    id: "tapscript-stack-story.v1",
    description: "Storyboard: one recorded success witness, opcode by opcode, with the stack as plates.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "tapscript-case",
    drawing: true,
  },
  {
    id: "tapscript-trace.v1",
    description: "Recorded, verified tapscript executions from Bitcoin Core's test cases, step by step.",
    minFixtures: 2,
    maxFixtures: 6,
    interactive: true,
    controls: ["Step a reviewed trace", "Compare success/failure fixtures", "Inspect signature count"],
    fixtureKind: "tapscript-case",
    drawing: true,
  },
  {
    id: "sigops-budget.v1",
    description: "The per-input signature budget of recorded witnesses: 50 plus witness size, 50 per signature.",
    minFixtures: 1,
    maxFixtures: 6,
    interactive: false,
    controls: [],
    fixtureKind: "tapscript-case",
    drawing: true,
  },
  {
    id: "tapscript-sig-pays.v1",
    description: "What a checked and an empty signature add to the budget and what their checks cost.",
    minFixtures: 1,
    maxFixtures: 6,
    interactive: false,
    controls: [],
    fixtureKind: "tapscript-case",
    drawing: true,
  },
  {
    id: "tapscript-op-success.v1",
    description: "The OP_SUCCESS case: a trapdoor in the decoder, against a script that runs and fails.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "tapscript-case",
    drawing: true,
  },
  {
    id: "tapscript-minimalif.v1",
    description: "OP_IF accepts only an empty vector or 0x01: a recorded witness that fits and one that does not.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "tapscript-case",
    drawing: true,
  },
  {
    id: "p2sh-commitment.v1",
    description: "The output as a box locked by a 20-byte hash; the redeem script hashes back to it.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "p2sh-spend",
    drawing: true,
  },
  {
    id: "p2sh-shape.v1",
    description: "Redeem scripts hashed into a fixed 23-byte output shape.",
    minFixtures: 1,
    maxFixtures: 4,
    interactive: false,
    controls: [],
    fixtureKind: "p2sh-spend",
    drawing: true,
  },
  {
    id: "p2sh-stack-story.v1",
    description: "Storyboard: a legacy P2SH spend's stack through both evaluations.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "p2sh-spend",
    drawing: true,
  },
  {
    id: "p2sh-two-stage.v1",
    description: "BIP 16's checks on pinned spends: push-only scriptSig, hash match, then the redeem script or witness.",
    minFixtures: 1,
    maxFixtures: 4,
    interactive: true,
    controls: ["Choose a pinned spend", "Step through both evaluations", "Reveal the redeem script"],
    fixtureKind: "p2sh-spend",
    drawing: true,
  },
  {
    id: "p2sh-failures.v1",
    description: "Storyboard: the same spend broken three ways, each failing at a different stage.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "p2sh-spend",
    drawing: true,
  },
  {
    id: "p2sh-wrapped.v1",
    description: "Where pinned P2SH spends carry their signatures: scriptSig or witness, with their weight.",
    minFixtures: 2,
    maxFixtures: 4,
    interactive: false,
    controls: [],
    fixtureKind: "p2sh-spend",
    drawing: true,
  },
  {
    id: "p2sh-limit.v1",
    description: "The 520-byte push limit and the fifteen-key multisig it allows.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "p2sh-spend",
    drawing: true,
  },
  {
    id: "timelock-ranges.v1",
    description: "nLockTime's 32 bits split at the threshold, and 16 value bits read as blocks or 512-second units.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "timelock-encoding",
    drawing: true,
  },
  {
    id: "timelock-not-a-lock.v1",
    description: "Storyboard, schematic: a future nLockTime proves a later spend but locks nothing; CLTV in the coin's script does.",
    minFixtures: 0,
    maxFixtures: 0,
    interactive: false,
    controls: [],
    fixtureKind: "timelock-case",
    drawing: true,
  },
  {
    id: "timelock-pinned-fields.v1",
    description: "Lock fields of transactions published in BIPs 143 and 174, as consensus reads them.",
    minFixtures: 1,
    maxFixtures: 6,
    interactive: false,
    controls: [],
    fixtureKind: "timelock-bip-tx",
    drawing: true,
  },
  {
    id: "timelock-fields.v1",
    description: "Bitcoin Core's CLTV/CSV test transactions as a gate of BIP 65's and BIP 112's checks; field changes pre-computed by the tested model.",
    minFixtures: 2,
    maxFixtures: 16,
    interactive: true,
    controls: ["Choose absolute or relative lock", "Change a fixture field", "Compare height and time units"],
    fixtureKind: "timelock-case",
    drawing: true,
  },
  {
    id: "timelock-sequence-bits.v1",
    description: "nSequence's 32 bits under BIP 68: disable flag, type flag and the 16-bit value.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "timelock-encoding",
    drawing: true,
  },
  {
    id: "timelock-csv-story.v1",
    description: "Storyboard: one Core CHECKSEQUENCEVERIFY case, check by check.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "timelock-case",
    drawing: true,
  },
  {
    id: "timelock-mtp.v1",
    description: "Schematic: the last 11 block timestamps sorted, the median being the clock time locks read.",
    minFixtures: 0,
    maxFixtures: 0,
    interactive: false,
    controls: [],
    fixtureKind: "timelock-case",
    drawing: true,
  },
  {
    id: "versionbits-field.v1",
    description: "nVersion as 32 bit cells.",
    minFixtures: 1,
    maxFixtures: 4,
    interactive: false,
    controls: [],
    fixtureKind: "versionbits-deployment",
    drawing: true,
  },
  {
    id: "versionbits-top-bits.v1",
    description: "Top-bit patterns as drawers.",
    minFixtures: 0,
    maxFixtures: 0,
    interactive: false,
    controls: [],
    fixtureKind: "versionbits-deployment",
    drawing: true,
  },
  {
    id: "versionbits-bit-reuse.v1",
    description: "Schematic: reusing a bit.",
    minFixtures: 0,
    maxFixtures: 0,
    interactive: false,
    controls: [],
    fixtureKind: "versionbits-deployment",
    drawing: true,
  },
  {
    id: "versionbits-threshold.v1",
    description: "Thresholds to scale.",
    minFixtures: 2,
    maxFixtures: 2,
    interactive: false,
    controls: [],
    fixtureKind: "versionbits-deployment|versionbits-guideline",
    drawing: true,
  },
  {
    id: "versionbits-boundary.v1",
    description: "Storyboard: a period boundary.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "versionbits-deployment",
    drawing: true,
  },
  {
    id: "versionbits-state-machine.v1",
    description: "BIP 9/8 states over a run of periods.",
    minFixtures: 1,
    maxFixtures: 4,
    interactive: true,
    controls: ["Step through retarget periods", "Choose a published deployment", "Toggle signalling count"],
    fixtureKind: "versionbits-deployment|versionbits-guideline",
    drawing: true,
  },
  {
    id: "versionbits-lifecycle.v1",
    description: "Storyboard: one deployment's life.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "versionbits-deployment",
    drawing: true,
  },
  {
    id: "versionbits-record.v1",
    description: "Recorded deployments, read back.",
    minFixtures: 1,
    maxFixtures: 4,
    interactive: false,
    controls: [],
    fixtureKind: "versionbits-deployment",
    drawing: true,
  },
  {
    id: "versionbits-bip8.v1",
    description: "BIP 8's two endings.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "versionbits-guideline",
    drawing: true,
  },
  {
    id: "wallet-path-levels.v1",
    description: "BIP 44's first example path as a ribbon of six segments, hardened levels above the account line.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "wallet-path-vector",
    drawing: true,
  },
  {
    id: "wallet-discovery.v1",
    description: "Storyboard, illustrative: account discovery and the gap limit, read from BIP 44.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "wallet-path-vector",
    drawing: true,
  },
  {
    id: "wallet-path-examples.v1",
    description: "BIP 44's examples table drawn as the tree its paths form.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "wallet-path-vector",
    drawing: true,
  },
  {
    id: "wallet-path-walk.v1",
    description: "Steps down a published BIP 44-shaped path level by level to the key and address, from BIP 84 and BIP 86 vectors.",
    minFixtures: 1,
    maxFixtures: 3,
    interactive: true,
    controls: ["Choose a published path scheme", "Step through path levels", "Switch receive/change"],
    fixtureKind: "wallet-path-vector",
    drawing: true,
  },
  {
    id: "wallet-xpub-reach.v1",
    description: "One account xpub and every published address below it, re-derived from the xpub alone.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "wallet-path-vector",
    drawing: true,
  },
  {
    id: "wallet-p2tr-story.v1",
    description: "Storyboard: BIP 86's derived key to internal key, tweak, output key and address.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "wallet-path-vector",
    drawing: true,
  },
  {
    id: "wallet-spend-layouts.v1",
    description: "Schematic: the scriptSig and witness a BIP 84 and a BIP 86 spend carry.",
    minFixtures: 0,
    maxFixtures: 0,
    interactive: false,
    controls: [],
    fixtureKind: "wallet-path-vector",
    drawing: true,
  },
  {
    id: "wallet-path-schemes.v1",
    description: "The same five-level tower under purposes 44, 84 and 86, and what comes out at the bottom.",
    minFixtures: 3,
    maxFixtures: 3,
    interactive: false,
    controls: [],
    fixtureKind: "wallet-path-vector",
    drawing: true,
  },
  {
    id: "descriptor-outputs.v1",
    description: "One public key and the four different output scripts in a published combo() expansion.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "descriptor-vector",
    drawing: true,
  },
  {
    id: "descriptor-sentence.v1",
    description: "One published descriptor laid out as a sentence of named parts.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "descriptor-vector",
    drawing: true,
  },
  {
    id: "descriptor-nesting.v1",
    description: "sh(wpkh(KEY)) as boxes inside boxes, read from the outside in, with its templates and child-0 script.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "descriptor-vector",
    drawing: true,
  },
  {
    id: "descriptor-template.v1",
    description: "pkh(KEY) filling BIP 381's template: the key's HASH160 in the one slot between fixed opcodes.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "descriptor-vector",
    drawing: true,
  },
  {
    id: "descriptor-spellings.v1",
    description: "Several spellings of one descriptor from BIP 381 giving one and the same script.",
    minFixtures: 2,
    maxFixtures: 4,
    interactive: false,
    controls: [],
    fixtureKind: "descriptor-vector",
    drawing: true,
  },
  {
    id: "descriptor-anatomy.v1",
    description: "Published descriptors from BIPs 380–386 split into their expressions, with keys, expanded scripts and the checksum check.",
    minFixtures: 1,
    maxFixtures: 10,
    interactive: true,
    controls: ["Choose a published descriptor", "Highlight a key expression", "Check the descriptor checksum"],
    fixtureKind: "descriptor-vector",
    drawing: true,
  },
  {
    id: "descriptor-read-story.v1",
    description: "Storyboard: a ranged wpkh() descriptor read part by part and expanded, one script per child.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "descriptor-vector",
    drawing: true,
  },
  {
    id: "descriptor-checksum.v1",
    description: "BIP 380's character-to-symbol expansion and checksum for one published descriptor.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "descriptor-vector",
    drawing: true,
  },
  {
    id: "descriptor-typo-forgery.v1",
    description: "BIP 380's valid and error-in-payload vectors, and the altered text with a recomputed checksum.",
    minFixtures: 2,
    maxFixtures: 2,
    interactive: false,
    controls: [],
    fixtureKind: "descriptor-vector",
    drawing: true,
  },
  {
    id: "descriptor-expressions.v1",
    description: "BIP 380's index of script expressions as a map of where each may appear.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "descriptor-index",
    drawing: true,
  },
  {
    id: "musig2-chain-view.v1",
    description: "Signers behind a boundary; what the chain sees of a MuSig2 key path spend: one key, one signature.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "musig2-session",
    drawing: true,
  },
  {
    id: "musig2-keyagg.v1",
    description: "MuSig2 key aggregation with coefficients in two key orders, against the plain sum of the keys.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "musig2-keyagg",
    drawing: true,
  },
  {
    id: "musig2-coefficients.v1",
    description: "Storyboard: the key-list hash, a hashed coefficient, and the second key's coefficient of 1.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "musig2-session",
    drawing: true,
  },
  {
    id: "musig2-rounds.v1",
    description: "BIP 327 signing sessions from the published sig_agg vectors: key aggregation, nonce round, session values, partial signatures, final BIP 340 signature.",
    minFixtures: 1,
    maxFixtures: 4,
    interactive: true,
    controls: ["Step through signing rounds", "Choose a published vector", "Reveal aggregated values"],
    fixtureKind: "musig2-session",
    drawing: true,
  },
  {
    id: "musig2-round-story.v1",
    description: "Storyboard: one published signing session, stage by stage, around the same table.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "musig2-session",
    drawing: true,
  },
  {
    id: "musig2-nonce-once.v1",
    description: "Schematic: a secret nonce is used by Sign once and then refused.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "musig2-session",
    drawing: true,
  },
  {
    id: "musig2-psig-checks.v1",
    description: "BIP 327's partial-signature verification cases and their outcomes.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "musig2-psig-checks",
    drawing: true,
  },
  {
    id: "sp-address.v1",
    description: "The parts of a version 0 silent payment address.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "sp-vector",
    drawing: true,
  },
  {
    id: "sp-ecdh.v1",
    description: "Storyboard, symbolic: Alice and Bob reach the same Diffie-Hellman point across an open network.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "sp-vector",
    drawing: true,
  },
  {
    id: "sp-derive-story.v1",
    description: "Storyboard: one published vector's full derivation, from address keys to the receiver's scan.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "sp-vector",
    drawing: true,
  },
  {
    id: "silent-payment-derivation.v1",
    description: "BIP 352 send-and-receive vectors: input keys, input hash, shared secret, outputs, and the receiver's scan.",
    minFixtures: 1,
    maxFixtures: 8,
    interactive: true,
    controls: ["Choose a published vector", "Switch sender/receiver view", "Reveal shared-secret steps"],
    fixtureKind: "sp-vector",
    drawing: true,
  },
  {
    id: "sp-input-eligibility.v1",
    description: "Which inputs of published BIP 352 vectors contribute a key to the shared secret.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "sp-eligibility",
    drawing: true,
  },
  {
    id: "sp-scan-loop.v1",
    description: "The receiver's scan as a counter that stops at the first missing output.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "sp-vector",
    drawing: true,
  },
  {
    id: "sp-labels.v1",
    description: "A receiver's labeled addresses share their scan-key characters.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "sp-vector",
    drawing: true,
  },
  {
    id: "bf-two-directions.v1",
    description: "BIP 37 vs BIP 157/158.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bf-block",
    drawing: true,
  },
  {
    id: "bf-element-sieve.v1",
    description: "A block's scripts sieved into the set.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bf-block",
    drawing: true,
  },
  {
    id: "golomb-rice-code.v1",
    description: "Golomb-Rice codes.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bf-golomb",
    drawing: true,
  },
  {
    id: "bf-build-story.v1",
    description: "Storyboard: building a filter.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bf-block",
    drawing: true,
  },
  {
    id: "bf-size.v1",
    description: "Filter sizes to scale.",
    minFixtures: 1,
    maxFixtures: 3,
    interactive: false,
    controls: [],
    fixtureKind: "bf-block",
    drawing: true,
  },
  {
    id: "gcs-filter.v1",
    description: "A wallet uses a filter to choose blocks; optional published examples explain the encoding.",
    minFixtures: 1,
    maxFixtures: 8,
    interactive: true,
    controls: ["Choose a wallet outcome", "Step through the wallet workflow", "Choose a published block", "Test a fixture script against the filter", "Reveal Golomb-Rice coding"],
    fixtureKind: "bf-block",
    drawing: true,
  },
  {
    id: "bf-query-story.v1",
    description: "Storyboard: match, miss, false match.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bf-block",
    drawing: true,
  },
  {
    id: "filter-header-chain.v1",
    description: "Filter headers, linked.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bf-chain",
    drawing: true,
  },
  {
    id: "bf-peer-check.v1",
    description: "Schematic: peers disagree.",
    minFixtures: 0,
    maxFixtures: 0,
    interactive: false,
    controls: [],
    fixtureKind: "bf-chain",
    drawing: true,
  },
  {
    id: "v1-v2-framing.v1",
    description: "v1 and v2 framing.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "v2-framing",
    drawing: true,
  },
  {
    id: "v2-eavesdropper.v1",
    description: "Schematic: listeners on v1 and v2.",
    minFixtures: 0,
    maxFixtures: 0,
    interactive: false,
    controls: [],
    fixtureKind: "v2-vector",
    drawing: true,
  },
  {
    id: "v2-ellswift.v1",
    description: "A 64-byte ElligatorSwift key.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "v2-vector",
    drawing: true,
  },
  {
    id: "v2-detect.v1",
    description: "v1 prefix vs v2 key.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "v2-vector",
    drawing: true,
  },
  {
    id: "v2-key-story.v1",
    description: "Storyboard: keys to a packet.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "v2-vector",
    drawing: true,
  },
  {
    id: "v2-handshake.v1",
    description: "The BIP 324 handshake, step by step.",
    minFixtures: 1,
    maxFixtures: 8,
    interactive: true,
    controls: ["Step through the handshake", "Choose a published packet vector", "Compare v1 and v2 framing"],
    fixtureKind: "v2-vector",
    drawing: true,
  },
  {
    id: "v2-terminator.v1",
    description: "The garbage terminator.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "v2-vector",
    drawing: true,
  },
  {
    id: "v2-packet-bytes.v1",
    description: "One packet, byte by byte.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "v2-vector",
    drawing: true,
  },
  {
    id: "v2-rekey.v1",
    description: "Nonces and keys across a rekey.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "v2-rekey",
    drawing: true,
  },
  {
    id: "bip322-formats.v1",
    description: "BIP 322 formats as envelopes.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bip322-formats",
    drawing: true,
  },
  {
    id: "bip322-message-hash.v1",
    description: "Two messages, two hashes.",
    minFixtures: 2,
    maxFixtures: 2,
    interactive: false,
    controls: [],
    fixtureKind: "bip322-vector",
    drawing: true,
  },
  {
    id: "bip322-virtual-tx.v1",
    description: "to_spend and to_sign as linked tickets.",
    minFixtures: 1,
    maxFixtures: 8,
    interactive: true,
    controls: ["Choose a published vector", "Switch to_spend/to_sign view", "Reveal the message hash"],
    fixtureKind: "bip322-vector",
    drawing: true,
  },
  {
    id: "bip322-witness.v1",
    description: "A multisig signature's witness stack.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bip322-vector",
    drawing: true,
  },
  {
    id: "bip322-choice.v1",
    description: "Schematic: which format.",
    minFixtures: 0,
    maxFixtures: 0,
    interactive: false,
    controls: [],
    fixtureKind: "bip322-formats",
    drawing: true,
  },
  {
    id: "bip322-verify-story.v1",
    description: "Storyboard: a verifier's steps.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bip322-vector",
    drawing: true,
  },
  {
    id: "bip322-verdicts.v1",
    description: "Three verdicts as stamps.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bip322-verdicts",
    drawing: true,
  },
  {
    id: "bip322-interpreter.v1",
    description: "The reviewed opcodes as a rack.",
    minFixtures: 1,
    maxFixtures: 1,
    interactive: false,
    controls: [],
    fixtureKind: "bip322-verdicts",
    drawing: true,
  },
  {
    id: "bip322-limits.v1",
    description: "Schematic: what a signature does not prove.",
    minFixtures: 0,
    maxFixtures: 0,
    interactive: false,
    controls: [],
    fixtureKind: "bip322-verdicts",
    drawing: true,
  },
];

export const RECIPE_MAP = /* @__PURE__ */ new Map(/* @__PURE__ */ RECIPES.map((r) => [r.id, r]));
